name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.7.0  # Update to the latest version

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.hestiakey }}

    - name: Deploy to VPS
      run: |
        ssh www_youssoufateoi@34.16.132.251 "cd /home/youssoufa/web/bsaffe.com/public_html && git pull origin master"
