name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -e {0}
    env:
      node-version: '16'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:       
      - name: Checkout code
        uses: actions/checkout@v2.5.4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          cd /home/youssoufa/web/bsaffe.com/public_html
          git pull origin master
          git status
          npm install --only=prod

