name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Add SSH Key and Update Known Hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -t rsa 34.16.132.251 >> ~/.ssh/known_hosts
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy to Server
      run: |
        ssh www_youssoufateoi@34.16.132.251 "cd /path/to/your/website && git pull origin master"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

